# Navigation Links

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: '#projects'
    weight: 20
  - name: Publications
    url: '#featured'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 40

# Link to a PDF of your CV from the menu later by adding:
#  - name: CV
#    url: uploads/cv.pdf
#    weight: 50
